---
- name: install monit
  sudo: yes
  apt: name=monit update_cache=yes


- name: allow localhost access in monit config
  sudo: yes
  lineinfile: dest=/etc/monit/monitrc line="{{ item }}"
  with_items:
    - "set httpd port 2812 and"
    - "use address localhost"
    - "allow localhost"


- when: enable_mail_alerts == True and smtp_use_tls == True
  name: set tls_option
  set_fact: smtp_tls_option="using tlsv1"


- when: enable_mail_alerts == True and smtp_use_tls != True
  name: set tls_option
  set_fact: smtp_tls_option=""


- when: enable_mail_alerts == True
  name: set mail server for notifications in monit
  lineinfile: dest=/etc/monit/monitrc line="{{ item }}"
  with_items:
    - "set mailserver {{ smtp_host }} port {{ smtp_port }} username {{ smtp_user }} password {{ smtp_password }} {{ smtp_tls_option }} with timeout 30 seconds"


- name: start monit & mark to be started on system reboots
  service: name=monit state=started enabled=yes


- name: add monit config for elixir app
  sudo: yes
  template:
    src: app.monit.j2
    dest: "/etc/monit/conf.d/{{ app_name }}.monit"


- name: add monit config for nginx
  sudo: yes
  template:
    src: nginx.monit.j2
    dest: "/etc/monit/conf.d/nginx.monit"

- name: reload monit
  sudo: yes
  service: name=monit state=reloaded
